增加两个shell脚本

diff --git a/src/main/shell/demoscr b/src/main/shell/demoscr
--- a/src/main/shell/demoscr
+++ b/src/main/shell/demoscr
@@ -1,7 +1,9 @@
+#!/bin/bash
+
 if [ $# -ne 2 ]
 then 
-	echo "ERROR : Number are not supplied"
-	echo "Usage : $0 number1 number2"
+	echo "ERROR : Number are not supplied" 1>&2
+	echo "Usage : $0 number1 number2" 1>&2
 	exit 1
 fi 
 ans=`expr $1 + $2`
